whatis("Name:        Anaconda3")
whatis("Version:     5.2")
whatis("Category:    applications, interpreters, languagesx")
whatis("Keywords:    application, interpreter, language")
whatis("URL:         https://www.anaconda.com/download/#linux")
whatis("Description: Python 3 distribution")

prepend_path("PATH","/share/sw/open/anaconda/3/bin")
setenv("CONDA_PYTHON_EXE","/share/sw/open/anaconda/3/bin/python")
setenv("CONDA_SHLVL","1")
setenv("CONDA_EXE","/share/sw/open/anaconda/3/bin/conda")
setenv("CONDA_PREFIX","/share/sw/open/anaconda/3")
setenv("_CONDA_PYTHON_SYSCONFIGDATA_NAME","_sysconfigdata_x86_64_conda_cos6_linux_gnu")
setenv("_CONDA_SET_LIBARCHIVE","LIBARCHIVE")
setenv("CONDA_BACKUP_HOST","x86_64-conda_cos6-linux-gnu")
setenv("CONDA_PROMPT_MODIFIER","(base)")
setenv("CONDA_DEFAULT_ENV","base")
prepend_path("PYTHONPATH","/share/sw/open/anaconda/3/bin")
