whatis("Name:        Freesurfer")
whatis("Version:     6.0.0")
whatis("Category:    applications, neuroimaging")
whatis("Keywords:    application, neuroimaging")
whatis("URL:         https://surfer.nmr.mgh.harvard.edu/")
whatis("Description: software package for the analysis and visualization of structural and functional neuroimaging data")
 
local USER=os.getenv("USER")
setenv("FREESURFER_HOME","/share/sw/open/freesurfer")
setenv("FIX_VERTEX_AREA","")
setenv("FMRI_ANALYSIS_DIR","/share/sw/open/freesurfer/fsfast")
setenv("FSFAST_HOME","/share/sw/open/freesurfer/fsfast")
setenv("FSF_OUTPUT_FORMAT","nii.gz")
setenv("FS_OVERRIDE","0")
setenv("FUNCTIONALS_DIR","/share/sw/open/freesurfer/sessions")
setenv("LOCAL_DIR","/share/sw/open/freesurfer/local")
setenv("MINC_BIN_DIR","/share/sw/open/freesurfer/mni/bin")
setenv("MINC_LIB_DIR","/share/sw/open/freesurfer/mni/lib")
setenv("MNI_DATAPATH","/share/sw/open/freesurfer/mni/data")
setenv("MNI_DIR","/share/sw/open/freesurfer/mni")
setenv("MNI_PERL5LIB","/share/sw/open/freesurfer/mni/share/perl5")
setenv("OS","Linux")
prepend_path("PATH","/share/sw/open/freesurfer/mni/bin")
prepend_path("PATH","/share/sw/open/freesurfer/tktools")
prepend_path("PATH","/share/sw/open/freesurfer/fsfast/bin")
prepend_path("PATH","/share/sw/open/freesurfer/bin")
setenv("PERL5LIB","/share/sw/open/freesurfer/mni/share/perl5")
setenv("SUBJECTS_DIR", pathJoin("/home/",USER,"/freesurfer/subjects/")) 

