whatis("Name: R")
whatis("Version: 4.0.0")
whatis("Category: tools")
whatis("URL: http://cran.cnr.berkeley.edu/")
whatis("Description: R")
prepend_path("PATH", "/share/sw/open/r/4.0.0/bin")
always_load("anaconda/3")
